name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json
      - name: Install dependencies
        run: npm ci --no-audit --no-fund
      - name: Run lint
        run: npm run lint

  test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json
      - name: Install dependencies
        run: npm ci --no-audit --no-fund
      - name: Run tests
        run: npm run test

  lint-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./server/package-lock.json
      - name: Install dependencies
        run: npm ci --no-audit --no-fund
      - name: Prisma Generate
        run: npm run generate
      - name: Run lint
        run: npm run lint

  test-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./server/package-lock.json
      - name: Install dependencies
        run: npm ci --no-audit --no-fund
      - name: Prisma Generate
        run: npm run generate
      - name: Run tests
        run: npm run test
